lib/openssl.c, lib/picotls.c
Some compile(ex Visual Studio C++ compiler) does not allow it.
=> Avoid arithmetic operator for void pointer

README.md, lib/picotls.c
Among the wire-level changes, picotls (at the moment) is affected by:
picotls is unaffected by the following changes, since it does not (yet) implement the features being mentioned:
* Remove the 0-RTT Finished, resumption_context, and replace with a psk_binder field in the PSK itself
* Restructure PSK key exchange negotiation modes
* Add max_early_data_size field to TicketEarlyDataInfo
* Add a 0-RTT exporter and change the transcript for the regular exporter
* Merge TicketExtensions and Extensions registry. Changes ticket_early_data_info code point
* Replace Client.key_shares in response to HRR
* Harmonize requirements about cipher suite matching: for resumption you need to match KDF but for 0-RTT you need whole cipher suite. This allows PSKs to actually negotiate cipher suites.
=> move to draft-17

CMakeLists.txt, deps/cifra/src/curve25519.tweetnacl.c, deps/cifra/src/ext/handy.h, lib/cifra.c, t/cli.c, t/minicrypto.c
Do not use non-standard expressions (e.g. `typeof`), nor use `for (type ...`.
=> Relax the compiler requirement

lib/openssl.c, t/openssl.c
as specified in the doc-comment of verify_certificate
=> `verify_sign` should free the key

include/picotls.h, lib/picotls.c, t/picotls.c
"Clients MAY send an empty client_shares vector in order to request group selection from the server at the cost of an additional round trip." ([draft 19 section 4.2.6](https://tlswg.github.io/tls13-spec/#key-share)).
=> add flag to force HRR

lib/picotls.c
Fixes #63.
Also changes the alert to `ILLEGAL_PARAMETER` when a client finds an unexpected cipher_suite is found in ServerHello.
=> include `cipher_suite` in HelloRetryRequest (a change in -19)

deps/cifra/src/curve25519.tweetnacl.c
The changes ought to be pretty small. There does not appear to be any effect on test. But look at the change in the function sel2119. It was previously:
> static void sel25519(gf p, gf q, int b)
> {
>    int64_t tmp, mask = ~(b-1);
That is, the argument "b" was declared as int and used as int64. This cannot be right, since the definition of int can vary with the machine architecture. I changed that to:
> static void sel25519(gf p, gf q, int64_t b)
> {
>    int64_t tmp, mask = ~(b-1);
This suppresses the warning. I hope that it respects the original intent.
=> Suppress warnings in curve25519.tweetnacl.c

lib/pembase64.c
@huitema Do we need this? I would appreciate it if you could see whether it's necessary or not.
=> fix out-of-bounds access in base64 decoder

include/picotls.h, lib/picotls.c, t/picotls.c
Implements stateless retry.
The PR adds following properties to `ptls_handshake_properties_t`.
* `server.cookie.enforce_use` - if the server should enforce the client to do a stateless retry
* `server.cookie.key` - secret used for signing / verifying the cookie (internally uses HMAC)
* `server.cookie.additional_data` - additional data to be used for signing / verification
If `server.cookie.enforce_use` is set and if `ptls_handshake` emits a stateless HelloRetryRequest, the function returns `PTLS_ERROR_STATELESS_RETRY`. In such case, the application should dispose the TLS object (i.e. the `ptls_t` object).
If `server.cookie.key` is non-NULL, `ptls_handshake` will try to handle the Cookie extension found in ClientHello. If the value is NULL, the function will return an handshake error when …
=> stateless retry (HelloRetryRequest with Cookie)

lib/picotls.c
In case of resumption, it is legal for a client to omit extensions that are not required for resumption. This is especially the case for KeyShares; delaying public key operation until the server responses with HRR makes perfect sense.
Thanks to @hannestschofenig.
=> allow ommission of extensions not necessary for resumption

lib/picotls.c
On server-side, picotls has been calculating the client application traffic secret when it receives ClientFinished. This has worked fine until draft-18.
However, in draft-21, EOED became a handshake message. Therefore the secret needs to be calculated before updating the hash with the received EOED.
This PR moves the calculation to when the server application traffic secret is calculated, achieving symmetry with the client-side code that also calculate the two secrets at the same time.
=> EOED is not part of the context when calculating traffic secret

include/picotls.h, lib/picotls.c, t/cli.c, t/minicrypto.c, t/openssl.c
Helps testing and also might help portability.
Considering the fact that `random_bytes` is a callback, it makes sense to have `get_time` defined as a callback as well.
Note that this is a compatibility-breaking change. Users would need to adjust how they setup `ptls_context_t`.
=> use callback for getting time

include/picotls.h, lib/picotls.c
and adds `is_early` argument to ptls_exporter_secret so that the value can be used.
fixes #95
=> retain early-exporter-master-secret after handshake

include/picotls/pembase64.h, lib/pembase64.c, lib/picotls.c, lib/uecc.c, picotlsvs/picotlsvs/picotlsvs.c, t/util.h
Fix for memleak issue reported in #85 as well as a related issue I found while testing with a certificate which contains multiple entries.
=> Fix memleak and potential crash in cli

include/picotls.h, lib/picotls.c, t/picotls.c
Add `base_label` as an optional argument to hkdf wrappers, so that QUIC implementations can specify `QUIC ` as a prefix as opposed to `tls13 `.
=> accept base-label as an argument

include/picotls.h, lib/picotls.c, t/picotls.c
In #102, retry and its statefulness became a tri-state option as shown below.
```
/**
* when a HRR with cookie should be sent
*/
typedef enum en_ptls_cookie_send_mode_t {
PTLS_COOKIE_SEND_NEVER = 0,
PTLS_COOKIE_SEND_ON_HRR,
PTLS_COOKIE_SEND_ALWAYS
} ptls_cookie_send_mode_t;
```
However in hindsight the design is wrong in sense that it does not provide an option to always send a stateful HRR.
The PR address the issue by turning the option into two booleans: `enforce_retry` and `retry_uses_cookie`.
Lastly, the PR updates the tests to cover the matrix of `enforce_retry` x `retry_uses_cookie`.
=> whether retry should be performed and whether it should be stateless are orthogonal issues

lib/picotls.c
Implements the sender-side of [Middlebox Compatibility mode](https://tlswg.github.io/tls13-spec/draft-ietf-tls-tls13.html#middlebox) defined in draft-23. We already have the receiver side, though we might want to prohibit the peer sending more than one ChangeCipherSpec record during handshake.
=> emit ChangeCipherSpec

lib/picotls.c
avoids a memory leak (2nd allocation of `tls->early_data`) and also fixes an assertion failure when the client requests resumption & exporter secret.
=> do not update early-data related data in second flight

lib/picotls.c
Fixes two issues.
* since #114, picotls has started to re-extract the secret upon receiving a HRR. This has caused handshake failures against servers that permit resumption even when HRR is involved (picotls does not allow that)
* picotls has always calculated "res binder" using the current transcript hash. The correct behavior is to use an empty transcript hash even when sending a PSK extension in the second CH.
fixes #124
=> fix handshake failure upon handling HRR + resumption

lib/picotls.c, t/picotls.c
Thereby allowing a client to do 0-RTT when the client's and server's preferred key-shares are different.
=> upon resumption, offer the key-share used to obtain the ticket in first flight

lib/openssl.c
LibreSSL 2.7 adds OpenSSL-compat APIs.
We can compile picotls with LibreSSL 2.7 after apply this patch.
If not, we get error messages like "HMAC_CTX_new already defined."
https://github.com/h2o/h2o/issues/1706#issuecomment-375651422
Tested with LibreSSL 2.7.0, LibreSSL 2.6.4, OpenSSL 1.0.2k (CentOS 7's) and OpenSSL 1.1.0g
=> Add supporting LibreSSL 2.7

include/picotls.h, lib/picotls.c, t/picotls.c
The AEAD API of picotls has been designed in hope that the only difference between the traffic key derivation functions of TLS 1.3 and QUIC will be the value of the base_label.
However, the function definition of QUIC has been changed recently, and draft-11 has shipped without reverting the change (see https://github.com/quicwg/base-drafts/issues/1255).
This PR changes the AEAD API of picotls so that it would be easier for the users to implement draft-11-style AEAD, as well as removing the abstraction that is no longer necessary.
https://gist.github.com/kazuho/6ace6cb277e977b89f283be7631b977f contains a code snippet that can be used to create an AEAD context for QUIC draft-11.
=> refactor AEAD API following changes in QUIC draft-11

include/picotls.h, include/picotls/openssl.h, lib/openssl.c, picotls.xcodeproj/project.pbxproj, t/cli.c, t/openssl.c
Adds secp384r1, secp521r1, X25519.
X448 is not implemented (since OpenSSL 1.1.0 does not support it; it is likely that 1.1.1 will have support). But the code is generic enough that it would be easy to add support for X448.
ToDo:
=> more key exchanges for the OpenSSL backend

include/picotls/openssl.h, lib/openssl.c, t/cli.c, t/openssl.c
We cannot support X25519 with libressl since the necessary functions are not provided.
regression caused by #148.
=> fix build failure when using libressl

include/picotls.h, lib/picotls.c
Following the discussion in https://github.com/quicwg/base-drafts/issues/1568, adds `hkdf_label_prefix` member to `ptls_context_t` so that the prefix can be changed to "quic ".
QUIC implementations should:
* set `ptls_context_t::hkdf_label_prefix` to "quic " <-- new!!!
* call `ptls_aead_new` with the last argument to set "quic "
The latter will continue to be a requirement, since AEAD is a layer that runs beneath the TLS layer without access to `ptls_context_t`.
=> API to change the label prefix used by key schedule

lib/cifra.c, picotlsvs/picotlsvs/picotlsvs.vcxproj, picotlsvs/testopenssl/testopenssl.vcxproj
This is a fix for issue #168.
The unit tests were failing for @lzq8272587 because of his windows system configuration. The failure happened when instantiating the "wincrypt" API before using CryptGenRandom in order to "read entropy" on Windows systems. The old "wincrypt" API requires opening a "security container" through the "CryptAcquireContext" API, and on LZQ system the access control configuration prevented user processes from doing that.
The fix is to use the more modern "bcrypt" API. The call to "BCryptGenRandom" does not require a security context, and thus is not subject to access control. 
The downside is that the "bcrypt" API is not available for Windows XP. We leave the old "wincrypt" code available under the "_WINDOWS_XP" compile flag, should someone really care about …
=> Replace wincrypt by bcrypt on modern Windows systems

include/picotls.h, lib/picotls.c
For example, the function will return 1 until it receives full EOED when 0-rtt is active. It can be used by the QUIC stacks to determine when it should supply epoch 2 crypto data to picotls.
fixes #175
=> new function `ptls_get_read_epoch` to return current read epoch

include/picotls.h, lib/picotls.c, t/picotls.c
Adds `ptls_context_t::omit_end_of_early_data` flag.
If set, `ptls_handle_message` does not emit an END_OF_EARLY_DATA message nor accepts it.
=> add `omit_end_of_early_data` flag

include/picotls.h, lib/openssl.c, lib/picotls.c, t/picotls.c
Some TLS hosts (e.g. 1.1.1.1) are identified by their IP addresses rather than the hostnames.
This PR implements validation for such hosts, specifically by making following changes:
* allow a string representing an IP address to be passed as an argument to `ptls_set_server_name`
* SNI extension is only sent if the supplied name is a DNS name
* call the appropriate function to verify a certificate based on IP address
=> verify certificate using IP address

include/picotls.h, lib/picotls.c, t/cli.c, t/picotls.c
The API changes are:
* `ptls_receive` returns `PTLS_ERROR_KEY_UPDATE_REQUESTED` when the peer requests a key update
* `ptls_key_update` should be called in response to peer requesting a key update, or when you want to initiate a key update
Such design has been chosen due to the fact that we cannot send a handshake message in `ptls_send` (because it is assumed that the output size does not increase except for the overhead of the record that carries application data).
=> implement key update

include/picotls.h, lib/picotls.c, t/cli.c, t/picotls.c
Picotls now handles key updates by itself. Specifically:
* `ptls_receive` never returns `PTLS_ERROR_KEY_UPDATE_REQUESTED`
* ciphertext returned from `ptls_send` may include a Key Update handshake message at any time
amends #183
=> automagically update the traffic key, unless `update_traffic_key` callback is used

CMakeLists.txt, include/picotls.h, include/picotls/certificate_compression.h, lib/certificate_compression.c, lib/picotls.c, picotls.xcodeproj/project.pbxproj, t/cli.c, t/picotls.c
Implements https://tools.ietf.org/html/draft-ietf-tls-certificate-compression-04.
* as a server:
* applications can supply their own callback that emits the Certificate message (or the equivalent)
* the new callback: `emit_certificate` replaces the `staple_ocsp` callback
* applications that have used the `staple_ocsp` callback needs to have it's own `emit_certificate` callback (example to be provided)
* `ptls_emit_compressed_certificate_t` is introduced for sending precompressed certificate chain
* `ptls_init_compressed_certificate` can be called during startup time to build the emit_certificate callback object. The function compresses the supplied certificates and the OCSP response (if provided).
* as a client:
* `decompress_certificate` can be used to register a decompression callback. …
=> support for precompressed certificates

lib/openssl.c
~Assert that `RAND_bytes()` and `EVP_CIPHER_CTX_cleanup()` were called successfully.~
Abort if `RAND_bytes()` and `EVP_CIPHER_CTX_cleanup()` ever fails.
`RAND_bytes()` is a fundamental cryptographic building block of the library, hence we should not assume that it will always succeed. Ditto for cleaning up the cipher context.
Here's an except From the OpenSSL documentation.
> RAND_bytes() and RAND_priv_bytes() return 1 on success, -1 if not supported by the current RAND method, or 0 on other failure.
> EVP_CIPHER_CTX_cleanup() returns 1 for success and 0 for failure.
Thanks to David Wong for reporting the concern.
=> Check the return value of critical OpenSSL functions

include/picotls/openssl.h, lib/openssl.c, t/cli.c, t/openssl.c
Fixes two issues:
* always use `*_HAVE_*` for feature macros. We were inconsistent in using HAVE or HAS. Use of `HAS_` will be deprecated.
* all feature detection macros will have the value set to `1` when the feature is available, allowing use of `#if PTLS_HAVE_XXX`
=> feature macros use *_HAVE_*

lib/picotls.c
Stop ignoring the `user_canceled(90)` alert description. As a result, all alerts are reported back to the caller of `handle_input()`, which is typically the Public API.
Allow the application to act on all alerts (e.g. log then close the connection). Another benefit is that `ptls_handshake()` will no longer returns success on `user_canceled` alert.
Reported by David Wong.
=> Handle all alert descriptions of both warning/fatal levels

include/picotls.h, lib/picotls.c
__tl;dr see the impact section__
Prefix of the labels being passed to HKDF functions are going to change in QUIC draft-17. The following table illustrates the changes (as well as clarifying what has been written in spec since -12 and what we have actually implemented).
||prefix for deriving handshake secrets|prefix for deriving traffic keys|
|:---:|:---:|:---:|
|**draft-16 (spec)**|"tls13 "|"quic "|
|**draft-16 (interop)**|"quic "|"quic "|
|**draft-17**|"tls13 "|"tls13 quic "|
|**configuration knob in picotls**|ptls_context_t::hkdf_label_prefix|label_prefix argument of ptls_hkdf_expand_label, ptls_aead_new|
The intent behind the changes in draft-17 are:
* to always use the "tls13 " prefix (to ensure that we would be deriving different traffic keys when using a future version of …
=> QUIC draft-17 support

.gitignore
It'd be wonderful if we could ignore CMake artifacts. They can be a little distracting when working on multiple branches. Thanks!
=> Ignore build tool artifacts

t/picotls.c
ASAN finding:
```
=================================================================
==24799==ERROR: AddressSanitizer: global-buffer-overflow on address 0x55841ae13761 at pc 0x55841aced3ec bp 0x7ffca51cae30 sp 0x7ffca51ca5e0
READ of size 48 at 0x55841ae13761 thread T0
#0 0x55841aced3eb in __asan_memcpy (/home/def/p/floss/picotls/test-openssl.t+0x1603eb)
#1 0x55841ad882db in ptls_hmac_create /home/def/p/floss/picotls/t/../lib/picotls.c:4680:5
#2 0x55841ad899e3 in ptls_hkdf_expand /home/def/p/floss/picotls/t/../lib/picotls.c:4709:25
#3 0x55841ad87dcd in hkdf_expand_label /home/def/p/floss/picotls/t/../lib/picotls.c:4751:11
#4 0x55841ad8a500 in ptls_hkdf_expand_label /home/def/p/floss/picotls/t/../lib/picotls.c:4764:12
#5 0x55841ad8a500 in get_traffic_key …
```
=> Make secrets as large as the maximum digest size, which is 48 for SHA384

lib/picotls.c
It's currently possible to run the code-path that decodes the cookies extension without providing the optional `ptls_handshake_properties_t` to `ptls_handshake()`, consequently killing the process. This PR adds a check before proceeding with the pointer.
The alert type for this case is: `illegal_parameter`
Thanks to David Wong for reporting the issue.
=> Check the properties pointer before proceeding

.travis.yml
Fix openssl path for build with macOS Builder (and avoid message build without openssl)
add new job with Xcode 10.1 (and clang-10)
=> Travis : enhance macos job

include/picotls.h, lib/picotls.c
pass the flag that indicates a status request was received or not to the cert emit callback. 
The server should not include the extension `PTLS_EXTENSION_TYPE_STATUS_REQUEST`, nor should it staple if the request wasn't received.
Without this change openssl-1.1.1 s_client produces the following error:
```
140737354049280:error:141B30D9:SSL routines:tls_collect_extensions:unsolicited extension:ssl/statem/extensions.c:628:
```
alternatively we can pass the flag all the way to `ptls_build_certificate_message` instead of relying on the ocsp_status iovec.
=> Only include status extension (OCSP) when requested

lib/picotls.c
picotls is returning decode error for such ClientHellos.
Regression in #155.
=> fix incorrect handling of CH.KeyShare containing multiple keys

CMakeLists.txt
As part of debugging the google/oss-fuzz integration I noticed that the `BUILD_FUZZER` build does not correctly instrument static libraries for coverage/feedback outside of `OSS_FUZZ` builds. This PR addresses that issue.
Here is coverage before (8 counters):
```
$ ./fuzz-server-hello -runs=4
INFO: Seed: 91409740
INFO: Loaded 1 modules   (8 inline 8-bit counters): 8 [0x6a0248, 0x6a0250),
INFO: Loaded 1 PC tables (8 PCs): 8 [0x48d1c0,0x48d240),
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
INFO: A corpus is not provided, starting from an empty corpus
#2  INITED cov: 4 ft: 4 corp: 1/1b exec/s: 0 rss: 32Mb
#4  DONE   cov: 4 ft: 4 corp: 1/1b exec/s: 0 rss: 32Mb
Done 4 runs in 0 second(s)
```
And after (3444 counters):
```
$ ./fuzz-server-hello …
```
=> Instrument dependencies in fuzz builds

lib/picotls.c
In the server: we reject a CH if it contains one empty protocol name. In
the client, reject the SH if the server responds with an empty protocol
name
=> Reject empty ALPN protocol names

include/picotls.h, lib/picotls.c, t/cli.c
For some historical reasons, when running as a client, picotls calculates the handshake write key when it receives EncryptedExtensions - the first handshake message protected by the handshake key  (FWIW, it made sense to do so a long time ago, when we used to send EOED and commission the handshake write key at this moment. We are now doing that at a later moment so that we could could continue sending early data until becoming possible to send 1-RTT data).
That does not work well with QUIC, a protocol that requires the TLS stack to provide handshake write key as soon as possible (consider the case of SH and EE being delivered as separate UDP datagrams).
This PR address the issue by moving the calculation of handshake write key to the earliest possible moment.
The unfortunate side-effect …
=> Expose handshake write key when receiving ServerHello

lib/openssl.c, t/openssl.c
Because EVP_DecryptUpdate retains one block, see evp_enc.c.
This has caused incorrect responses in quicly's CID decryption function, leading to packet misrouting.
=> Use EVP_EncryptUpdate for ECB decryption

lib/picotls.c, t/picotls.c
Bugs being fixed:
The expected behavior in terms of protocol is, quoting from RFC 8446 section 4.2.10:
> A server which receives an “early_data” extension MUST behave in one of three ways:
> * (snip)
> * Request that the client send another ClientHello by responding with a HelloRetryRequest. A client MUST NOT include the “early_data” extension in its followup ClientHello. The server then ignores early data by skipping all records with external content type of “application_data” (indicating that they are encrypted), up to the configured max_early_data_size.
=> fix client-side bugs when receiving HRR in response to a 0-RTT resumption attempt

include/picotls.h, lib/picotls.c
This PR exposes the raw cipher list offered by the client to the client hello callback via `ptls_on_client_hello_parameters_t`.
Alternatively, could also keep it as an iovec and decode within the callback or right before calling it, but  this way the decoding is kept within `decode_client_hello`.
thanks!
=> expose the list of the ciphers offered by the client

CMakeLists.txt
I believe that there's no need to compile each of the individual source files.
=> ptlsbench should link against picotls-minicrypto library

lib/minicrypto-pem.c
It's possible that byte_index goes past last_byte1 after we read the
OID. Add a check for that.
Credit to OSS-Fuzz
=> Fix heap-buffer-overflow READ

t/cli.c
I use `t/cli.c` for some testing, and noticed that it doesn't send an alert when it closes a connection. Could you please review this small patch? The patch updates `t/cli.c` with the following:
- send an `close_notify` alert before it closes the connection
- print a couple of messages which show that the server started and waits for connections
=> Send an alert in cli

fuzz/fuzz-asn1.c, include/picotls.h, lib/minicrypto-pem.c
`ptls_context_t` is a public structure that retains properties of the TLS context. Whenever state needs to be associated, a callback object should be used. Regarding the particular issue, a private key is retained as part of the `ptls_sign_certificate_t` callback object.
An attempt to cleanly fix #226.
=> Remove ptls_context_t::pkey_buf

include/picotls.h, lib/picotls.c
The callback-based API introduced in #241 was difficult to use, as the back pointer needs to be setup at an appropriate moment.
This PR reverts the introduction of that API, and instead introduces a boolean flag that can be get / set indicating if the TLS connection is being traced.
=> simplify tracing

include/picotls.h, lib/cifra/random.c, lib/picotls.c
This is the most practical way of passing parameters to picotls upon instantiation from application (e.g., h2o) to picotls through layers in between (e.g., quicly).
=> introduce `ptls_default_skip_tracing` TLS global

include/picotls.h, lib/picotls.c
Providing the raw [ClientHello](https://tools.ietf.org/html/rfc8446#section-4.1.2) value via the `on_client_hello` callback is beneficial to developers in various ways -- Analytics, Fingerprinting and etc.
The raw message is already available within `server_handle_hello()`. Therefore it's just a matter of additional assignment when initializing `ptls_on_client_hello_parameters_t`. The developer is responsible for copying the value for further processing of the data in their callback / system.
=> Enable developers to access the raw client_hello message

include/picotls.h, lib/picotls.c
`encrypt_ticket` is the callback interface that allows an application to intervene with the resumption.
At the moment, returning zero from the callback means that the ticket has been decrypted, and that 0-RTT is acceptable. Returning a non-zero value means that the ticket has been rejected (due to decryption failure or whatever). There is no way for an application to indicate that 0-RTT is forbidden even though the ticket has been decrypted (and that it can be used for resuming the session).
This PR adds a new error code: PTLS_ERROR_REJECT_EARLY_DATA, that indicates the case.
Note: applications that want to associate arbitrary data to the session ticket are expected to customize the encrypt_ticket callback for attaching / detaching that arbitrary data.
=> API to reject 0-RTT (while accepting resumption)

include/picotls.h
This PR fixes two warnings in Visual Studio in the public interface header.
```
picotls\include\picotls.h(450,6): warning C4201: nonstandard extension used: nameless struct/union
picotls\include\picotls.h(498,21): warning C4214: nonstandard extension used: bit field types other than int
```
=> Fix Visual Studio compiler warnings

include/picotls.h, lib/picotls.c
@larseggert Does something like this help?
=> `ptls_default_skip_tracing` can be a constant when tracing is not used

.travis.yml, include/picotls.h, lib/picotls.c, t/picotls.c
Introduces `ptls_context_t::max_buffer_size`.
When set to a non-zero value, indicates the maximum amount of memory that can be used for buffering TLS handshake messages. picotls will return handshake_failure when receiving a partial handshake message that does not fit into the buffer.
=> cap buffer size

include/picotls/openssl.h
OpenSSL exposes OPENSSL_NO_CHACHA and OPENSSL_NO_POLY1305 when either no-chacha
or no-poly1305 flags are passed to OpenSSL at build time which disables it.
Signed-off-by: James Taylor <james@jtaylor.id.au>
=> Fix check for ChaCha_Poly1305 detection

lib/openssl.c
EVP_CIPHER_CTX_cleanup is deprecated and optionally unavailable.
=> openssl: use EVP_CIPHER_CTX_reset

include/picotls.h, lib/openssl.c, lib/picotls.c, t/picotls.c
* imports BUILD_ASSERT from h2o, quicly.
* add IS_ARRAY macro based on the suggestion by @mattn (https://twitter.com/mattn_jp/status/1250205966286467073)
* add ELEMENTSOF that uses the IS_ARRAY macro
=> add PTLS_ELEMENTSOF for counting the number of elements in an array

t/cli.c
Without the added check `enc.off == 0`, we were pushing new encrypted data to `ptls_send` every time we iterate through the event loop.
That builds up the encrypted buffer (`encbuf`), but the amount of data stored there eventually plateaus, as the cost of removing the first bytes from `encbuf` (as those first bytes have been passed to the kernel through `write`) becomes the bottleneck of the CPU.
=> add more data to `ptbuf` (plaintext buffer) only when encbuf is empty

include/picotls.h, lib/picotls.c, t/cli.c
Namely,
* as a server, send CCS regardless of the configuration, if the client sends one (this is a MUST in RFC 8446 Appendix D.3)
* raise UNEXPECTED_MESSAGE when emission of CCS is required while using a protocol that does not use TLS records (e.g., QUIC)
* in the example client, use compatibility mode
amends #305.
=> Various changes related to ChangeCipherSpec

lib/fusion.c, t/fusion.c
The attempt of this PR is to reduce the code size while manually unrolling the loops, as sugessted by @herumi.
While manual unrolling does not provide performance improvement on my testbed (Core i5 9400, Ubuntu 19.10), we see comparable performance with less than half the code size.
||object size|1440 bytes|16384 bytes|
|:---:|---:|---:|---:|
|original (-O3)|5696|0.293|2.804|
|original (-O2 -fno-unroll-loops)|4480|0.332|3.245|
|this PR (-O3)|5808|0.294|2.813|
|this PR (-O2 -fno-unroll-loops)|2480|0.297|2.893|
Object sizes are in bytes, other cells are in seconds (i.e. smaller the better). In addition to the command options listed above, `-DNDEBUG -march-native` were used in common.
=> Optimize for size, while unrolling the hottest loops

include/picotls.h
Is has been discovered that Xcode prior to version 10 cannot correctly
detect if an expression is an array.
```
struct s {
int a[10];
};
void fun(const struct s *s)
{
PTLS_ASSERT_IS_ARRAY_EXPR(s->a);
}
````
Clang in older Xcode returns false for the above PTLS_ASSERT_IS_ARRAY_EXPR,
while it should be true. Removing the const qualifier from the parameter
declaration resolves the issue.
See https://github.com/h2o/quicly/pull/306#issuecomment-626037269 for details.
Clang in Ubuntu seems to be fine, even with older versions.
=> Add workaround for array detection in Xcode <10

lib/picotls.c
This pull request reduces stack usage by doing the following:
* Reduce the excess size of, or eliminate the use of "smallbuf" (i.e., the stack-allocated buffer provided to ptls_buffer_t to reduce calls on malloc-free), when the cost of other operations (e.g., crypto) is expected to dwarf the performance improvement that we'd would gain from not using malloc.
* allocate `st_ptls_client_hello_t` on heap
* lazy-allocate certain objects
In master, the top 20 functions that consume stack space are as follows:
```
1640	server_handle_hello
616	hkdf_expand_label
608	client_handle_new_session_ticket
536	try_psk_handshake
504	client_handle_encrypted_extensions
392	ptls_handshake
344	build_esni_contents_hash
328	handle_certificate
296	send_certificate_and_certificate_verify
280 …
```
=> reduce stack usage

lib/openssl.c
fix leak while keeping with, I presume, the original intention behind using `EVP_CIPHER_CTX_reset()` instead of `EVP_CIPHER_CTX_new/EVP_CIPHER_CTX_free`
=> fix leak cipher ctx leak in ptls_openssl_(en/dec)crypt_ticket() calls

lib/picotls.c
Up until now, picotls has been accepting early data when the ticket being used was issued while the context allowed the use of early data.
This PR changes the behavior so that picotls would reject early data when configured to not offer the use of early data.
Thanks to @robguima.
=> reject early data if configured as such

.travis.yml
Up until now, surprisingly, only OpenSSL 1.0.2 was used.
=> Adjusts CI matrix to use openssl 1.0.2, 1.1.0, libressl 3.2.5

lib/openssl.c
Minor change in the raw public code, replace 
```
ptls_iovec_t expected_pubkey = {};
```
By:
```
ptls_iovec_t expected_pubkey = { 0 };
```
=> Fix compile error on windows.

include/picotls/openssl.h, lib/openssl.c, lib/picotls.c
when using a custom certificate verification callback in [picoquic_enable_custom_verify_certificate_callback](https://github.com/private-octopus/picoquic/blob/0c18817bfdeffd74ff860ef1e8e13c4e357e40fa/picoquic/tls_api.c#L1275) currently no algo values are installed on the callback object, so we get segfaulted in `push_signature_algorithms` during the handshake.
the algo values are hidden inside openssl.c, and `ptls_openssl_init_verify_certificate` allocates an `X509_STORE` if you pass in `NULL` so i figured this is the best solution?
also SNI was broken for me. but adopting this new way corrects it.
and openssl says...
> Applications are strongly advised to use this interface in preference to explicitly calling X509_check_host(3), hostname checks may be out of scope with the DANE-EE(3) …
=> Use X509_VERIFY_PARAM for certificate verification

include/picotls.h, lib/picotls.c
Before this change picotls was doing client preference order selection
unconditionally.
=> Introduce a `server_cipher_preference` knob to allow changing which end drives the cipher selection

include/picotls.h, lib/cifra/aes128.c, lib/cifra/aes256.c, lib/cifra/chacha20.c, lib/openssl.c
So as to not break source-level compatibility of existing programs that define their own `ptls_cipher_suite_t` using compound literal expression with positional parameters, the `name` field is added at the end of `ptls_cipher_suite_t`.
=> add `const char *ptls_cipher_suite_t::name` that contains the name of the cipher

include/picotls.h, lib/cifra/x25519.c, lib/openssl.c, lib/uecc.c
Does the same thing as #355 for negotiated groups.
Source compatibility is also retained here, by adding the `name` field at the end of the struct.
=> add name field to `ptls_key_exchange_algorithm_t`

lib/openssl.c, t/cli.c, t/util.h
This PR adds `-V` option to the cli command that allows users specify custom cert stores, and also makes sure that the `verify_cert_chain` function respects the verification parameters associated to the cert store.
Some context regarding the latter point: in #347 we switch to using `X509_VERIFY_PARAM` for verifying the SNI. Unfortunate side effect of the new approach was that it replaced the verify params associated to `X509_STORE`, by creating a new `X509_VERIFY_PARAM` and then setting it to the context using `X509_STORE_CTX_set0_param`.
This PR changes the approach to one instead modifies the verify parameters associated to `X509_STORE_CTX`. By doing so, the properties (e.g., `X509_V_FLAG_PARTIAL_CHAIN`) inherited from `X509_STORE` by calling `X509_STORE_CTX_init` remains in effect. …
=> `-V` option for specifying cert store, use verify params of the cert store

t/openssl.c
In OpenSSL 3.0, EVP implementation of blowfish was moved to the legacy provider. As the provider is not enabled by default, we have to enable it explicitly.
=> fix test failure when openssl 3.0 is being used

t/util.h
Although `utils.h` header is not included in the API of the library, it has a lot of useful utility functions.
When this file is included in a C++ project, there are certain conversion errors the compiler is complaining about.
This PR fixes them.
```shell
/picotls/t/util.h: In function ‘int util_save_ticket_cb(ptls_save_ticket_t*, ptls_t*, ptls_iovec_t)’:
/picotls/t/util.h:91:42: error: invalid conversion from ‘void*’ to ‘st_util_save_ticket_t*’ [-fpermissive]
struct st_util_save_ticket_t *self = (void *)_self;
^~~~~~~~~~~~~
/picotls/t/util.h: In function ‘void setup_esni(ptls_context_t*, const char*, ptls_key_exchange_context_t**)’:
/picotls/t/util.h:183:28: error: invalid conversion from ‘void*’ to ‘ptls_esni_context_t** {aka st_ptls_esni_context_t**}’ [-fpermissive]
if ((ctx->esni = …
```
=> Conversion fixes for utils.h

CMakeLists.txt
Currently, compiling with `cmake -B build` and `make -C build` we get binaries
that are linked with libssl and libcrypto. According to the README, the OpenSSL
backend only depends on libcrypto, not libssl. So I changed the build to use the
`OPENSSL_CRYPTO_LIBRARIES` variable. I ran all the tests on my machine and they
all passed so I don't think I broke anything. This doesn't just affect the
example executables, if anyone consuming this library used CMake I think they
would get libssl too.
=> Make OpenSSL backend link only libcrypto.

include/picotls.h
From gcc:
- error: redundant redeclaration of ‘ptls_iovec_init’ [-Werror=redundant-decls]
- error: "PICOTLS_USE_DTRACE" is not defined, evaluates to 0 [-Werror=undef]
From clang:
- missing field 'off' initializer [-Werror,-Wmissing-field-initializers]
=> Fix build errors

include/picotls.h, lib/cifra/aes-common.h, lib/cifra/chacha20.c, lib/fusion.c, lib/openssl.c, lib/picotls.c, lib/ptlsbcrypt.c, picotlsvs/bcrypt-test/bcrypt-test.c, t/picotls.c
At the moment, the encrypt API provided by picotls only receives one `ptl_iovec_t`, which in turn produces an AEAD record. This leads to inefficiency when multiple fragments of data has to be sent concatenated.
To give an example, HTTP/2 implementations typically split HTTP response into small chunks, prepending HTTP/2 frame headers to each of those chunks, before they pass them to the TLS stack. At the moment, HTTP/2 implementations have to either:
* a) build a flat image that has the HTTP/2 frame headers and chunks of response being concatenated, or
* b) call `ptls_send` for encrypting the HTTP/2 frame header, then make a separate call for encrypting the response chunk.
_a_ is inefficient when the implementation already has the response buffered in memory, because an extra copy would be …
=> vectorized encrypt API

.github/ISSUE_TEMPLATE/custom.md, README.md, SECURITY.md
Hello,
This PR adds a [github.com security policy](https://help.github.com/en/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository) to the picotls repo, similar to the one [we added to h2o](https://github.com/h2o/h2o/pull/2356). Like the h2o PR, it also adds a basic [Github Issue Template](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository). Together, these changes should result in:
- A Github Issue workflow that directs users to report security issues privately
- Explicitly capturing the security policy using up-to-date github.com conventions
The security policy aims to reflect the existing vulnerability coordination and disclosure policies for picotls. Feedback and direct edits from maintainers …
=> Add SECURITY.md

.github/workflows/ci.yml, CMakeLists.txt, include/picotls.h, include/picotls/fusion.h, lib/cifra/aes128.c, lib/cifra/aes256.c, lib/cifra/chacha20.c, lib/fusion.c, lib/openssl.c, lib/picotls.c, lib/ptlsbcrypt.c, picotls.xcodeproj/project.pbxproj, t/fusion.c
This PR implements "non-temporal aes-gcm" engine, that uses non-temporal store instructions when emitting encrypted bytes. When doing zero-copy to NIC, use of ordinary store instructions requires 2x the main memory bandwidth compared to what is actually being sent, because when an ordinary store instruction is issued against an uncached memory location, the CPU has to read that cache line into cache before updating part of that line (note: L3 cache is so small compared to the sum of the send buffers for all the connections inflight). By using non-temporal store instructions, the new engine avoids this read ("read-for-ownership" in terms of MOESI).
ToDo:
Builds on top of #385.
Older result: as of e0caecc, aes128gcm (16KB block) throughput, compared to openssl (ubuntu 20.04):
||gcc (nt …
=> non-temporal aes-gcm engine

t/fusion.c
gfmul on Zen 3 does 256-bit access.
=> fix out-of-bounds access in test

.github/workflows/ci.yml, t/fusion.c
In https://github.com/h2o/picotls/pull/398#issuecomment-1179993518, @huitema says:
> On the tests: I observed yesterday that my simple PR was failing sometimes, because some tasks were taking too long -- especially the ASAN/UBSAN runs. You may want to use a reduced set of tests for the ASAN/UBSAN action.
I agree, we need a progress bar, otherwise GitHub Actions thinks the test has stalled.
=> show progress to prevent GitHub Actions killing CI

t/cli.c, t/util.h
This cleaner PR replaces PR #411 which was mixed up with too many old commits.
The warning happens when compiling `t/cli.c` because the return arguments of calls to `write` are not checked. In theory, casting the calls as `(void)` should suffice, but that does not work with `gcc` . Further analysis showed that return code should in fact be checked, because the calls can be interrupted, and in that case it would be better to repeat them.
In order to keep the code simple and readable, the PR proposes adding a macro in `t/util.h`, then use that macro to protect the `write` calls.
=> Fix compile warnings about unchecked returns in t/cli

src/esni.c, t/openssl.c
This PR replaces Pr #413, which included too many unrelated commits. The changes affect `src\esni.c` and `t\openssl.c`. The file `esni.c` is only used in tests of ESNI with Visual Studio; the changes there handle the use of providers instead of engines when using OpenSSL 3.0. There are two minor change in `t/openssl.c`. First, not try using the `engine` APIs and load the default module instead when using OpenSSLv3 -- as written, the code relied only on a `OPENSSL_NO_ENGINE` variable, which was not automatically set when using OpenSSL 3.0. Second, undefining the variable `OPENSSL_API_COMPAT` before including `lib/openssl.c`, because that variable is defined again inside `lib/openssl.c`, and Visual Studio protests against redefinition.
The changes resolve issue #412.
=> Fix Visual Studio warnings when using OpenSSL 3.0

.github/workflows/ci.yml
OpenSSL 3.x is already covered by `macOS / OpenSSL 3.x`, but it would be better to have `Linux / OpenSSL 3.0` as well. It's very easy to add because we have already an Ubuntu 22.04 image.
=> ci: use Ubuntu 22.04 to test picotls with OpenSSL 3.0

lib/fusion.c, t/fusion.c
Fixes three issues in `ptls_fusion_aesgcm_set_capacity` which is called when the AEAD input supplied to the fusion engine is longer than 1500 bytes:
* fix read overrun
* correctly initialize the additional ghash precalculated vectors
* clear the precalculated ghash vectors of the old context before calling `free`
Tests are added to cover the use of the function.
Closes #418, subsumes #419.
=> [fusion] fix heap read overrun when handling AEAD of > 1500 bytes

include/picotls/openssl.h, lib/openssl.c
This change adds the following new ticket functions which use OpenSSL v3 EVP_MAC_CTX.  HMAC APIs are deprecated in OpenSSL v3.  EVP_MAC_CTX is its replacement.
- ptls_openssl_encrypt_ticket_evp
- ptls_openssl_decrypt_ticket_evp
=> Add ticket functions which use OpenSSL v3 EVP_MAC_CTX

include/picotls.h, include/picotls/openssl.h, lib/openssl.c, lib/picotls.c, t/picotls.c
One way of fixing the cancellation bug is to remove support for cancellation.
When using asynchronous signing, users are "required" to retain `ptls_t` until the async operation is complete.
Alternative to #423.
=> [async signing] no cancellation

include/picotls.h, t/cli.c, t/minicrypto.c, t/openssl.c
… with existing code that uses positional initialization of a struct.
Amends #426.
=> move `tls12_cipher_suites` to the end to improve source compatibility

include/picotls.h, lib/picotls.c
At one point during the development of QUIC v1, we thought that separation within the TLS handshake protocol was necessary (#158). But we decided to not do that, and the field was marked obsolete (#192).
Now that QUIC v1 has shipped, let's revert the unnecessary complexity altogether (modulo keeping the field in the context for source compatibility).
=> go back to the old way hard-coding the HKDF label prefix

.github/workflows/cifuzz.yml
Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR.
This is a service offered by OSS-Fuzz where picotls already runs. CIFuzz can help detect catch regressions and fuzzing build issues early, and has a variety of features (see the URL above). In the current PR the fuzzers gets build on a pull request and will run for 300 seconds.
Signed-off-by: David Korczynski <david@adalogics.com>
=> ci: add CIFuzz Github action

include/picotls.h, lib/picotls.c
When attempting to read one byte, there are cases where we have to raise either DECODE_ERROR (indicating a syntax error) or another error (e.g., ILLEGAL_PARAMETER indicating logical error).
It is better to have a wrapper function like `ptls_decode16`.
=> `ptls_decode8` for consistency

lib/openssl.c
That's what libssl does, it'd be less confusing to do the same.
Amends #422.
=> [async] turn off by default

include/picotls.h, lib/picotls.c, t/picotls.c
Would be useful for observing expiry of HTTPS / SVC RRs.
=> provide API to obtain ECH config_id being used

lib/fusion.c
`aligned_alloc` is unavailable on Windows and we map that to `_aligned_malloc` at [lib/fusion.c line 63](https://github.com/h2o/picotls/blob/master/lib/fusion.c#L63).
[Official documentation of _aligned_malloc](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/aligned-malloc?view=msvc-170) states: _Don't use free, which doesn't reclaim the aligned memory correctly and can lead to hard-to-diagnose bugs._
=> [fusion][windows] Use `_aligned_free`

include/picotls.h, include/picotls/openssl.h, lib/openssl.c, t/openssl.c
Exposes utility functions, generalizes the concept of fd-based notification, adds callback-based notification.
=> alternative signers: support callback-based method, add utility functions

lib/picotls.c
This commit adds missing log_event callback invocation when an application uses its own record layer.  While such application may use update_traffic_key callback to log secrets, it still be useful to share log_event callback with a regular TLS application.
=> Add missing log_event when application uses its own record layer

include/picotls.h, lib/picotls.c
Instead of exposing a parsed list of cipher-suites (that might have been cut down at the end), expose the raw vector.
Reverts #227, closes #462.
If necessary, we can do the same for other properties (e.g., `server_certificate_types`), or if we want to go to the extreme, for all types include those that have complicated structures (e.g., `alpn`, `signature_algorithms`).
=> expose raw cipher-suite list from on_client_hello callback

lib/openssl.c
It seems that since #310, openssl AEAD backend have been testing if supplied `key` is NULL and returning success if that is the case, while other backends have continued to assume `key` is non-NULL and crash if a NULL keys is supplied.
I believe this was an unintentional change is #310 and nobody is passing a NULL key (this call path can executed only once per object and passing a NULL key makes AEAD unusable), and therefore this PR removes that `if`.
=> [openssl backend] remove unnecessary check

include/picotls.h, lib/cifra/aes-common.h, lib/cifra/chacha20.c, lib/fusion.c, lib/openssl.c, lib/picotls.c, lib/ptlsbcrypt.c
rather than just providing `xor_iv`.
For context, some backends have had a loophole that allows callers set full-IV, but that loophole was closed in https://github.com/h2o/picotls/pull/466.
=> provide API for fully rewriting IV

t/cli.c
It looks like this function was orphaned as part of a refactor in https://github.com/h2o/picotls/commit/13038d50fbf9eaa8a202802c22db661cb6e4b392. It triggers a GCC warning
=> Removed unused static function find_kem in t/cli.c

include/picotls.h, lib/picotls.c, t/picotls.c
Add a new boolean flag to determine if chacha20 should be reprioritized to the top of the server cipher list in case it happens to appear at the top of the client cipher list.
This is meant to cater to clients which may lack AES HW acceleration, and/or may prefer chacha20.
It should work similarly to OpenSSL's `SSL_OP_PRIORITIZE_CHACHA` CTX option.
=> Add support for chacha20 cipher prioritization

include/picotls.h
The function is defined, but not used internally.
It was not exposed in the public interface either, even though `ptls_import()` was.
=> Add ptls_export() prototype to picotls.h

CMakeLists.txt
Fix a typo. `FATAL ERROR` should be `FATAL_ERROR`.
=> cmake: "FATAL ERROR" -> FATAL_ERROR

t/cli.c
=> [cli] regonise aegis cipher-suites

lib/cifra/x25519.c, lib/openssl.c, t/picotls.c
RFC 7748 states we may fail if the derived key is all-zero, RFC 8446 states we MUST.
In the OpenSSL backend we do the check (to be accurate OpenSSL does), but we have not been doing anything on the side of minicrypto and boringssl.
This implements the checks, as well as fixing memory leaks that happen when an error is returned from the derivation function (minicrypto), clearing secrets used (boringssl).
=> [minicrypto][boringssl] x25519 key derivation must fail when output is all-zero

cmake/fusion.cmake
Error message of https://github.com/h2o/h2o/issues/3289 indicates that some i386 environments might have access to AVX2 but not to `_mm_insert_epi64` because the latter takes a 64-bit int as an argument.
This PR adds the invocation of `_mm_insert_epi64` to the test code used for checking if fusion can be used, so that fusion would be disabled on environments that lack support for the intrinsic.
=> maybe `_mm_insert_epi64` is unavailable on i386?

lib/picotls.c
=> key_schedule_new might fail due to malloc failing

lib/openssl.c
`evp_keyex_init` is called from two locations. Both of them assume that if the functions returns zero (success) the ownership of `pkey` is transferred to `evp_pkey_init`, or if the function returns non-zero (failure) the reference count of `pkey` remains as-is.
However, `evp_keyex_init` has been inconsistent in what to do upon failure; it has been retaining reference count as-is if `malloc` failed, but has been decrementing the reference count if `EVP_PKEY_get1_tls_encodedpoint` failed.
This PR address the latter, making sure that if an error is returned the reference count remains as-is.
=> [evp_keyex_init] keep refcount unchanged when the function fails

.github/workflows/mbedtls.yml, CMakeLists.txt, cmake/FindMbedTLS.cmake, include/picotls/ptls_mbedtls.h, lib/ptls_mbedtls.c, t/ptls_mbedtls.c, t/ptlsbench.c
The goal of this PR is to support MbedTLS as an alternative to OpenSSL, especially on "embedded" platforms.
The first milestone is to verify that CMake and Make work properly and produce a library `picotls-mbedtls` and a test program `t.mbedtls` when using the option "WITH_MBEDTLS=ON". The current set of supported algorithms is minimal -- mainly, aes128_gcm with sha256. MbedTLS supports a much larger range of algorithm, which will be added later.
=> Ptls mbedtls

include/picotls.h, t/picotls.c
Up until now, when generating TLS messages, we have ignored the overflow of length fields. When they overflow, we have been sending length fields that contains the modulo of the actual length.
This does not happen in practice (as the endpoints control what they send in the handshake messages, which tend to be much smaller than the limits), and even if they fail the behavior is not harmful in sense that they end up in TLS handshake failures, but it is better to report them as errors.
Therefore, this PR adds such logic. A new error code is defined that would be reported to the application. The error code sent on wire will be Internal Error, which is the same error code that we send when running out of memory.
=> detect and report TLS buffer overflows

include/picotls.h, lib/picotls.c, t/picotls.c
This adds the ability to transfer the traffic secrets from one TLSv1.3  tls structure to another newly created one.
New helper functions are added to `t/picotls.c`:  `alloc_and_migrate_tls_context()` is a function that simulates the usage of import/export in different code paths and handshake types; `aead_keys_cmp()` compares secrets and keys (sequence numbers as well) to determine whether the transfer was correctly done.
@kazuho was in the loop as an active contributor, but we both agreed the PoC (private branch) code needed some cleanup--some of which already included in this PR.
One new thing form the PoC was adding an explicit call to `key_schedule_new()` to create a new `key_schedule` , so that key updates would work (tests that include key updates would work as well).
=> adds TLS13 support for ptls_import() and ptls_export()

lib/openssl.c
Currently the client always verifies the server name against the server's cert.
This change would allow the client to skip the name verification (as the server does) if a NULL server name is provided.
This would primarily be to allow the use of servers/clients on a local network without hostnames.
It would also be the first step to resolving this Picoquic issue: https://github.com/private-octopus/picoquic/issues/1184
=> Allow client to verify certificate with NULL server name

include/picotls.h, lib/openssl.c
Improve key exchange comments and fix typo in method name `ecdh_generate_key`.
=> Refine key exchange comments and fix typo

include/picotls/openssl.h
When buidling LibreSSL + picotls with `-Wundef` option, the build fails due to the following error.
```
2024-06-16T05:50:37.9131759Z In file included from /home/runner/work/ngtcp2/ngtcp2/ngtcp2-1.6.0-DEV/crypto/picotls/picotls.c:36:
2024-06-16T05:50:37.9134332Z /home/runner/work/ngtcp2/ngtcp2/picotls-libressl/include/picotls/openssl.h:91:5: error: 'PTLS_OPENSSL_HAVE_CHACHA20_POLY1305' is not defined, evaluates to 0 [-Werror,-Wundef]
2024-06-16T05:50:37.9136125Z #if PTLS_OPENSSL_HAVE_CHACHA20_POLY1305
2024-06-16T05:50:37.9136719Z     ^
2024-06-16T05:50:37.9138515Z /home/runner/work/ngtcp2/ngtcp2/picotls-libressl/include/picotls/openssl.h:108:5: error: 'PTLS_OPENSSL_HAVE_CHACHA20_POLY1305' is not defined, evaluates to 0 [-Werror,-Wundef]
2024-06-16T05:50:37.9140294Z #if …
```
=> Fix build error due to undefined variables

t/cli.c
As reported by https://github.com/h2o/picotls/issues/521, the args of `getopt()` misses `u`
and so it does not parse the `-u` option even though it is implemented.
This patch parses the `-u` option via `getopt`.
Fix https://github.com/h2o/picotls/issues/521
=> Add the `u` option to the getopt arg to parse

picotlsvs/bcrypt-test/bcrypt-test.vcxproj, picotlsvs/fusiontest/fusiontest.vcxproj, picotlsvs/picotls-bcrypt/picotls-bcrypt.vcxproj, picotlsvs/picotls-core/picotls-core.vcxproj, picotlsvs/picotls-fusion/picotls-fusion.vcxproj, picotlsvs/picotls-minicrypto-deps/picotls-minicrypto-deps.vcxproj, picotlsvs/picotls-minicrypto/picotls-minicrypto.vcxproj, picotlsvs/picotls-openssl/picotls-openssl.vcxproj, picotlsvs/picotlsvs/picotlsvs.vcxproj, picotlsvs/ptlsbench/ptlsbench.vcxproj, picotlsvs/testopenssl/testopenssl.vcxproj
The old Windows SDK version 10.0.17763.0 is not supported anymore, so go for the next one, 10.0.18362.0
=> Target windows SDK 10.0.18362.0

include/picotls.h, lib/picotls.c, t/cli.c, t/picotls.c
=> add support for ticket_request extension (RFC 9149)

include/picotls.h, lib/picotls.c, t/cli.c
This PR expands the support for sampling-based tracing through Unix sockets.
Connections to be traced can be selected based on the combination of the following criteria:
* sampling ratio - a `float` between 0 and 1
* any number of SNIs
* any number of client IP addresses
* if or not to include application data
Unlike the old USDT-based scheme (as has been provided by h2olog), the new interface allows each logger to specify different criteria. Up to 32 loggers are supported.
As we transition from using USDT to Unix sockets, sampling support is removed from the USDT side. Otherwise, USDT probes are retained as-is, as they are considered valuable properties when debugging the system as a whole with picotls or h2o being part of the system.
=> sampling-based tracing through Unix sockets

lib/picotls.c
Cherry-pick from https://github.com/h2o/h2o/pull/3424.
=> in case of external PSK mode, clients need not provide `properties`

lib/picotls.c
The function send_certificate_verify is used both in client and server mode. When it is used in client mode, the server part of the union in struct st_ptls_t is not supposed to be read. Moreover the client part is larger than the server part, e.g. on x86_64:
sizeof(st_ptls_t.client): 120
sizeof(st_ptls_t.server):  80
It means that server.async_job may not be NULL when calling the function in client mode.
=> send_certificate_verify: remove invalid assert in client mode

cmake/dtrace-utils.cmake
As of ubuntu focal (20.04), ` systemtap-sdt-dev` version `4.2-3ubuntu0.1`, the temporary files collide in a build with concurrency (`make` `-j`).
The description in the systemtap repo commit [0de9020c9](https://sourceware.org/git/?p=systemtap.git;a=commit;h=0de9020c970bceda73e32bbd169c12e7579f21ec) describes the problem.  From what I can tell, that commit introduced the version that we see on focal and it has the problem that we run into in a parallel build of h2o, because as the description mentions:
> Note: this still leaves open a race in the case of 2 dtrace processes with identical input/output paths.
`dtrace` does not take all that long to run, the impact that serializing all `dtrace` command invocations has on the build time is imperceptible.
The eventual fix in …
=> Force serialization of `dtrace` `-G` invocations.

lib/picotls.c
This is a trivial change on top of https://github.com/h2o/picotls/commit/bbcdbe6dc31ec5d4b72a7beece4daf58098bad42
Older macOS requires `<sys/socket.h>` to come before other related headers.
=> Minor fix to headers sequence

README.md
`libaegis` was moved to the `aegis-aead` organization a long time ago.
=> Update the repository location for libaegis

lib/picotls.c
Provide a fallback for macOS versions where `pthread_threadid_np` is not available.
=> Add a fallback for missing pthread_threadid_np on macOS
