h2o/picotls

- lib/picotls.c
Fixes the issues found in #7.
https://www.ietf.org/mail-archive/web/tls/current/msg21664.html (thanks to Ilari)
> fixups for draft-17 support

- lib/picotls.c
Also adjusts the client to send PSKExchangeModes always when session ticket store callback is non-NULL.
> send NewSessionTicket only when client sends PSKExchangeModes

- include/picotls.h
- lib/cifra.c
- lib/openssl.c
- lib/picotls.c
- t/picotls.c
> send NewSessionTicket immediately after ServerFinished

- include/picotls.h
- lib/picotls.c
- t/cli.c
> expose API / add option to cli command for logging secrets

- include/picotls.h
- include/picotls/minicrypto.h
- include/picotls/openssl.h
- lib/openssl.c
- lib/picotls.c
- lib/uecc.c
- t/cli.c
- t/minicrypto.c
- t/openssl.c
- t/picotls.c
This is what OpenSSL does, and ends up in less code.
> allow user to swap TLS context when handling SNI

- .gitignore
- include/picotls.h
- lib/cifra.c
- lib/openssl.c
- lib/picotls.c
- lib/uecc.c
- picotlsvs/picotls/ReadMe.txt
- picotlsvs/picotls/picotls.vcxproj
- picotlsvs/picotls/picotls.vcxproj.filters
- picotlsvs/picotls/targetver.h
- picotlsvs/picotls/wincompat.h
- picotlsvs/picotls/wintimeofday.c
- picotlsvs/picotlsvs.sln
- picotlsvs/picotlsvs/ReadMe.txt
- picotlsvs/picotlsvs/picotlsvs.c
- picotlsvs/picotlsvs/picotlsvs.vcxproj
- picotlsvs/picotlsvs/picotlsvs.vcxproj.filters
- picotlsvs/picotlsvs/targetver.h
I created a Visual Studio project in a side directory. Two projects in fact: an empty console application that I intend to use for running a few tests, and a WIN32 library. At this point, it compiles on Windows with just 2 warnings. I did a  couple of changes in the code to add references to Windows headers when compiling WIN32 project, and also to suppress compiler warnings. Please review!
> Port to Visual Studio

- include/picotls.h
- lib/cifra.c
- lib/openssl.c
- lib/picotls.c
- t/cli.c
- t/minicrypto.c
- t/picotls.c
- t/test.h
> add elements for QUIC

- CMakeLists.txt
- include/picotls/openssl.h
- lib/cifra.c
- lib/openssl.c
- picotls.xcodeproj/project.pbxproj
- t/openssl.c
- t/picotls.c
> add support for chacha20-poly1305

- deps/cifra/src/curve25519.tweetnacl.c
- lib/picotls.c
This enabled me to achieve interop with Mozquic/NSS
> Adding support for HRR without Key Share extension

- t/cli.c
- t/util.h
Enable listening on IPv6 address and allow localhost to be resolved to either IP version.
> cli: add -4 and -6 option, fix IPv6 server support

- lib/picotls.c
- t/picotls.c
> split large handshake message into multiple TLS records

- lib/picotls.c
One change from draft-18 to draft-21 (supported in #59) is that end-of-early-data is indicated using a handshake message rather than an alert.
The fact means that when generating a NewSessionTicket immediately after ServerFinished, the server needs to take the existence of the message into consideration when expecting what the client-sent handshake messages would be.
ToDo:
> fix handshake failure when using session ticket is generated from a 0-RTT handshake

- lib/picotls.c
- t/minicrypto.c
a.k.a. pretend like TLS 1.2 resumption
> draft-22 support

- t/cli.c
to check streaming early-data behavior, early-data vs. HRR interaction, etc.
> fully-async operation in cli

- picotlsvs/picotlsvs/picotlsvs.c
> Apply changes in ptls_export_secret to picotlsvs.

- lib/picotls.c
There is no reason to restrict access to the cipher-suite using which the client is trying to resume a session. And QUIC needs this.
So QUIC applications need to call `ptls_handshake` then call `ptls_get_cipher`. If a non-NULL value is returned, then resumption is in action. So the client may use the obtained cipher (and the exported key) to send 0-RTT data. If NULL is returned, then the session will never resume.
> allow use of `ptls_get_cipher` during resumption

- include/picotls.h
- lib/picotls.c
- t/picotls.c
> add new mode that uses cookie when HRR is to be sent but does not enforce use of HRR

- lib/cifra.c
- lib/openssl.c
- lib/picotls.c
- t/openssl.c
- t/picotls.c
> correctly calculate handshake hash when offering multiple selection

- include/picotls.h
- lib/picotls.c
```
ptls_t *tls;
void *my_data;
...
// set
*ptls_get_data_ptr(tls) = my_data;
// get
my_data = *ptls_get_data_ptr(tls);
```
> provide hook to associate application data to `ptls_t`

- lib/picotls.c
> implement draft-26

- lib/picotls.c
Adds support for newer drafts that do not have any change at the wire level. The hope is that we can add the final version to the list as well.
> add support for draft-27, -28

- lib/picotls.c
For testing Wireshark using picoquic. Key log format:
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Key_Log_Format
Tested with picotls server against openssl client, EXPORTER_SECRET
matches. EARLY_EXPORTER_SECRET was not tested (picotls somehow rejects
the 0RTT data).
___
Tested with:
```
picotls$ ./cli -l /tmp/keys2 -c server.pem -k server.pem localhost 4433
openssl$ ./openssl s_client -connect localhost:4433 -quiet -keylogfile /tmp/keys
```
(sort keys and keys2, then compare)
Tried testing early data (run `openssl` first with `-sess_out sess.pem`, then `-sess_in sess.pem -early_data some.txt`) and while `EARLY_EXPORTER_SECRET` is visible in OpenSSL's keylog file, it is not visible in picotls's key log file. OpenSSL without `-quiet` also shows that early data was …
> Support logging (early) exporter secret

- include/picotls.h
- lib/pembase64.c
- picotlsvs/picotlsvs/picotlsvs.c
> Pem file const

- lib/picotls.c
See the doc-comment on on_client_hello callback.
> saving the server_name is the responsibility of the on_client_hello callback

- lib/picotls.c
This is what have been suggested in the comment, however has long been implemented differently. It has not been an issue because `tls->server_name` has also been updated in a different way than
expected. But the latter issue has been fixed in #154, and now we see the problem.
> Check SNI of 2nd CH only when the value of the 1st CH has been saved

- lib/picotls.c
> cap max size of early-data to skip (currently hard-coded to 64K)

- include/picotls/certificate_compression.h
- lib/certificate_compression.c
- t/cli.c
- t/e2e.t
> build two types of pre-compressed certificate chain (OCSP stapling)

- lib/picotls.c
- t/picotls.c
it's a corner-case bug, but it's a bug. And it's a good way to run tests.
> fix bug that generates broken ClientHello when offering a ticket not saving new ones

- t/ptlsbench.c
Series of simple fixes for benchmark issues when running on Ubuntu.
> Fix bench bug

- lib/picotls.c
The condition has been the opposite.
> generate exporter secrets when and only when requested

- t/cli.c
When using the cli command for some tests (e.g., HTTP/2), it is undesirable to shutdown the send-side immediately after the test scenario has been sent.
See also: #240
> add option (-I) for keeping the send-side open

- include/picotls.h
- lib/picotls.c
- t/picotls.c
To be merged once quic draft-26 ships.
> add codec for quic varint

- t/cli.c
For detail, see the help message of `-B`.
> add option for throughput benchmark

- include/picotls.h
- t/cli.c
> avoid buggy `__builtin_types_compatible_p` in GCC 4.x, 5.x

- lib/openssl.c
> Fix potential NULL dereference

- picotls.xcodeproj/project.pbxproj
Iinstead of assuming that one is installed in /usr/local/openssl-1.1.0.
> [xcode] for openssl, rely on homebrew

- include/picotls.h
- lib/picotls.c
- t/picotls.c
> knob to select cipher-suite based on server's preference

- t/picotls.c
Amends #345.
Huge thanks to @huitema, I was able to figure out that #345 broke Windows build and was able to fix it myself!
> MSVC fixes

- lib/ptlsbcrypt.c
> add names to bcrypt-backed ciphers

- .github/workflows/ci.yml
- misc/docker-ci.mk
To follow those reviews: https://github.com/h2o/quicly/pull/496#discussion_r760830356 https://github.com/h2o/quicly/pull/496#discussion_r760830410
> [CI][trivial] less quotes for workflow files; declare vars in makefiles

- lib/openssl.c
- t/openssl.c
> set correct role, confirm behavior using cert w. EKU=serverAuth only

- include/picotls.h
> Default code should use new API

- include/picotls.h
- lib/picotls.c
> add API to obtain traffic keys for offloading

- include/picotls.h
> fix C++ compile error

- lib/picotls.c
> we support one more extension

- lib/picotls.c
> don't use alloca

- include/picotls.h
- lib/picotls.c
Thanks to @ha0li for the code.
> add support for CERTIFICATE_AUTHORITIES extension

- CMakeLists.txt
- include/picotls/mbedtls.h
- lib/mbedtls_sign.c
- t/mbedtls.c
subsumes #501, with the following changes:
* merge master HEAD
* apply clang-format
> MbedTLS sign certificate

- t/cli.c
Cherry-pick from #543. Closes #543.
> error exit if O_NONBLOCK fails, as cli would probably not work

- include/picotls.h
- lib/picotls.c
> refactor ptlslog for simplicity and less code size

- lib/picotls.c
> add includes (otherwise fails to compile on freebsd)

- README.md
Spotted by @torokati44 -- Thanks!
> Update README.md: three -> four
